
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE `hoba`;
USE hoba;

CREATE TABLE `adr` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `EXTADR` varchar(255) DEFAULT NULL,
  `LOCALITY` varchar(255) DEFAULT NULL,
  `PCODE` decimal(20,0) DEFAULT NULL,
  `STREET` varchar(255) DEFAULT NULL,
  `REGION_ADR_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKFC8FA467E46B` (`REGION_ADR_HJID`)
)  ;

CREATE TABLE `cdm` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LANGUAGE_` varchar(255) DEFAULT NULL,
  `ORGUNIT_CDM_HJID` bigint(20) DEFAULT NULL,
  `PROGRAM_CDM_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK1040C1A2EDE30` (`PROGRAM_CDM_HJID`),
  KEY `FK1040C35DAF2D0` (`ORGUNIT_CDM_HJID`)
)  ;

CREATE TABLE `contactdata` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TELEPHONE` varchar(255) DEFAULT NULL,
  `ADR_CONTACTDATA_HJID` bigint(20) DEFAULT NULL,
  `CONTACTNAME_CONTACTDATA_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK82CA97AA12B0FE52` (`CONTACTNAME_CONTACTDATA_HJID`),
  KEY `FK82CA97AA678D0632` (`ADR_CONTACTDATA_HJID`)
)  ;

CREATE TABLE `contacts` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONTACTDATA_CONTACTS_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKCD35053170D743F` (`CONTACTDATA_CONTACTS_HJID`)
)  ;

CREATE TABLE `course` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID` varchar(255) DEFAULT NULL,
  `IDENT` varchar(255) DEFAULT NULL,
  `LEVEL_` varchar(255) DEFAULT NULL,
  `TEACHINGTERM` varchar(255) DEFAULT NULL,
  `COURSECODE_COURSE_HJID` bigint(20) DEFAULT NULL,
  `COURSEDESCRIPTION_COURSE_HJID` bigint(20) DEFAULT NULL,
  `COURSENAME_COURSE_HJID` bigint(20) DEFAULT NULL,
  `CREDITS_COURSE_HJID` bigint(20) DEFAULT NULL,
  `FORMALPREREQUISITES_COURSE_H_0` bigint(20) DEFAULT NULL,
  `LEARNINGOBJECTIVES_COURSE_HJ_0` bigint(20) DEFAULT NULL,
  `RECOMMENDEDPREREQUISITES_COU_0` bigint(20) DEFAULT NULL,
  `SYLLABUS_COURSE_HJID` bigint(20) DEFAULT NULL,
  `TEACHINGACTIVITY_COURSE_HJID` bigint(20) DEFAULT NULL,
  `TEACHINGPLACE_COURSE_HJID` bigint(20) DEFAULT NULL,
  `COURSE_CDM_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK76D5D41BD75D1F25` (`COURSEDESCRIPTION_COURSE_HJID`),
  KEY `FK76D5D41B4DF2EBD7` (`TEACHINGPLACE_COURSE_HJID`),
  KEY `FK76D5D41B43336B6B` (`SYLLABUS_COURSE_HJID`),
  KEY `FK76D5D41BEAD89307` (`LEARNINGOBJECTIVES_COURSE_HJ_0`),
  KEY `FK76D5D41B5C9FE9B5` (`FORMALPREREQUISITES_COURSE_H_0`),
  KEY `FK76D5D41BACF354F9` (`TEACHINGACTIVITY_COURSE_HJID`),
  KEY `FK76D5D41B4F4BCBFE` (`RECOMMENDEDPREREQUISITES_COU_0`),
  KEY `FK76D5D41BBEA437F4` (`COURSENAME_COURSE_HJID`),
  KEY `FK76D5D41B64A7BCA1` (`COURSE_CDM_HJID`),
  KEY `FK76D5D41BCA520C91` (`COURSECODE_COURSE_HJID`),
  KEY `FK76D5D41B8AD18637` (`CREDITS_COURSE_HJID`)
)  ;

CREATE TABLE `coursecode` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODESET` varchar(255) DEFAULT NULL,
  `VALUE_` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `coursedescription` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `credits` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ECTSCREDITS` varchar(255) DEFAULT NULL,
  `CONTENT` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `degree` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEGREE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `formalprerequisites` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `infoblock` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERDEFINED` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `infoblockcontentitem` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TEXT` longtext,
  `ITEMSUBBLOCK_INFOBLOCKCONTEN_0` bigint(20) DEFAULT NULL,
  `CONTENTITEMS_INFOBLOCK_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKFA10BD0D74BA2998` (`ITEMSUBBLOCK_INFOBLOCKCONTEN_0`),
  KEY `FKFA10BD0D74BA855` (`CONTENTITEMS_INFOBLOCK_HJID`)
)  ;

CREATE TABLE `learningobjectives` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `orgunit` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LANGUAGE_` varchar(255) DEFAULT NULL,
  `ORGUNITACRONYM` varchar(255) DEFAULT NULL,
  `ORGUNITID` varchar(255) DEFAULT NULL,
  `CONTACTS_ORGUNIT_HJID` bigint(20) DEFAULT NULL,
  `ORGUNITDESCRIPTION_ORGUNIT_H_0` bigint(20) DEFAULT NULL,
  `ORGUNITKIND_ORGUNIT_HJID` bigint(20) DEFAULT NULL,
  `ORGUNITNAME_ORGUNIT_HJID` bigint(20) DEFAULT NULL,
  `WEBLINK_ORGUNIT_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKE30A0248B68E0FCA` (`ORGUNITDESCRIPTION_ORGUNIT_H_0`),
  KEY `FKE30A02487970BB72` (`CONTACTS_ORGUNIT_HJID`),
  KEY `FKE30A02485AE51454` (`WEBLINK_ORGUNIT_HJID`),
  KEY `FKE30A0248945FAF2C` (`ORGUNITNAME_ORGUNIT_HJID`),
  KEY `FKE30A02486EADAB4` (`ORGUNITKIND_ORGUNIT_HJID`)
)  ;

CREATE TABLE `orgunitdescription` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `orgunitkind` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORGTYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `profession` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `program` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID` varchar(255) DEFAULT NULL,
  `IDENT` varchar(255) DEFAULT NULL,
  `LEVEL_` varchar(255) DEFAULT NULL,
  `PROGRAMID` varchar(255) DEFAULT NULL,
  `USERDEFINED` varchar(255) DEFAULT NULL,
  `FORMALPREREQUISITES_PROGRAM__0` bigint(20) DEFAULT NULL,
  `INFOBLOCK_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  `LEARNINGOBJECTIVES_PROGRAM_H_0` bigint(20) DEFAULT NULL,
  `PROGRAMCODE_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  `PROGRAMDESCRIPTION_PROGRAM_H_0` bigint(20) DEFAULT NULL,
  `PROGRAMNAME_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  `PROGRAMSTRUCTURE_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  `QUALIFICATION_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  `TEACHINGPLACE_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  `WEBLINK_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK185AAA64E92B5838` (`TEACHINGPLACE_PROGRAM_HJID`),
  KEY `FK185AAA64CA15610C` (`FORMALPREREQUISITES_PROGRAM__0`),
  KEY `FK185AAA64FE7DC336` (`PROGRAMSTRUCTURE_PROGRAM_HJID`),
  KEY `FK185AAA646B84F8CE` (`PROGRAMDESCRIPTION_PROGRAM_H_0`),
  KEY `FK185AAA642C11FF0E` (`LEARNINGOBJECTIVES_PROGRAM_H_0`),
  KEY `FK185AAA64915CC8D8` (`INFOBLOCK_PROGRAM_HJID`),
  KEY `FK185AAA6440652618` (`PROGRAMCODE_PROGRAM_HJID`),
  KEY `FK185AAA64D5851DB8` (`WEBLINK_PROGRAM_HJID`),
  KEY `FK185AAA642F195278` (`QUALIFICATION_PROGRAM_HJID`),
  KEY `FK185AAA646008CBF4` (`PROGRAMNAME_PROGRAM_HJID`)
)  ;

CREATE TABLE `programcode` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODESET` varchar(255) DEFAULT NULL,
  `VALUE_` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `programdescription` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SUBBLOCK_PROGRAMDESCRIPTION__0` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK1E24C6F889A6D5B2` (`SUBBLOCK_PROGRAMDESCRIPTION__0`)
)  ;

CREATE TABLE `programsearchworditem` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ITEM` varchar(255) DEFAULT NULL,
  `SEARCHWORDITEMS_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK3D8C7A292D6979CE` (`SEARCHWORDITEMS_PROGRAM_HJID`)
)  ;

CREATE TABLE `programstructure` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `HEADER` varchar(255) DEFAULT NULL,
  `SUBBLOCK_PROGRAMSTRUCTURE_HJ_0` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK8D6A036FD43B165D` (`SUBBLOCK_PROGRAMSTRUCTURE_HJ_0`)
)  ;

CREATE TABLE `qualification` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREDITS_QUALIFICATION_HJID` bigint(20) DEFAULT NULL,
  `DEGREE_QUALIFICATION_HJID` bigint(20) DEFAULT NULL,
  `PROFESSION_QUALIFICATION_HJID` bigint(20) DEFAULT NULL,
  `QUALIFICATIONDESCRIPTION_QUA_0` bigint(20) DEFAULT NULL,
  `QUALIFICATIONNAME_QUALIFICAT_0` bigint(20) DEFAULT NULL,
  `STUDYQUALIFICATION_QUALIFICA_0` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK941CB5CFCBBC8EB` (`PROFESSION_QUALIFICATION_HJID`),
  KEY `FK941CB5CFE84E9E6B` (`DEGREE_QUALIFICATION_HJID`),
  KEY `FK941CB5CF7AB0E148` (`QUALIFICATIONDESCRIPTION_QUA_0`),
  KEY `FK941CB5CFFC858CD` (`CREDITS_QUALIFICATION_HJID`),
  KEY `FK941CB5CFA96DB6D8` (`STUDYQUALIFICATION_QUALIFICA_0`),
  KEY `FK941CB5CFFDE8EE5B` (`QUALIFICATIONNAME_QUALIFICAT_0`)
)  ;

CREATE TABLE `qualificationdescription` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `recommendedprerequisites` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `refcourse` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IDREF` varchar(255) DEFAULT NULL,
  `REF_` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `refprogram` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IDREF` varchar(255) DEFAULT NULL,
  `REF_` varchar(255) DEFAULT NULL,
  `REFPROGRAM_PROGRAMSTRUCTURE__0` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKB5E516919254E9C1` (`REFPROGRAM_PROGRAMSTRUCTURE__0`)
)  ;

CREATE TABLE `region` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `studyqualification` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `subblock` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERDEFINED` varchar(255) DEFAULT NULL,
  `SUBBLOCK_SYLLABUS_HJID` bigint(20) DEFAULT NULL,
  `SUBBLOCK_STUDYQUALIFICATION__0` bigint(20) DEFAULT NULL,
  `SUBBLOCK_RECOMMENDEDPREREQUI_0` bigint(20) DEFAULT NULL,
  `SUBBLOCK_QUALIFICATIONDESCRI_0` bigint(20) DEFAULT NULL,
  `SUBBLOCK_PROFESSION_HJID` bigint(20) DEFAULT NULL,
  `SUBBLOCK_LEARNINGOBJECTIVES__0` bigint(20) DEFAULT NULL,
  `SUBBLOCK_FORMALPREREQUISITES_0` bigint(20) DEFAULT NULL,
  `SUBBLOCK_COURSEDESCRIPTION_H_0` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKB2D8DE4D8C6BC3DD` (`SUBBLOCK_LEARNINGOBJECTIVES__0`),
  KEY `FKB2D8DE4D9EE03E9` (`SUBBLOCK_PROFESSION_HJID`),
  KEY `FKB2D8DE4D30AF3A7C` (`SUBBLOCK_FORMALPREREQUISITES_0`),
  KEY `FKB2D8DE4D71387EE2` (`SUBBLOCK_QUALIFICATIONDESCRI_0`),
  KEY `FKB2D8DE4DA166C4C9` (`SUBBLOCK_SYLLABUS_HJID`),
  KEY `FKB2D8DE4D9A3DC78B` (`SUBBLOCK_COURSEDESCRIPTION_H_0`),
  KEY `FKB2D8DE4D8AF7F08A` (`SUBBLOCK_RECOMMENDEDPREREQUI_0`),
  KEY `FKB2D8DE4DA5D67CDD` (`SUBBLOCK_STUDYQUALIFICATION__0`)
)  ;

CREATE TABLE `subblockcontentitem` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TEXT` longtext,
  `ITEMREFCOURSE_SUBBLOCKCONTEN_0` bigint(20) DEFAULT NULL,
  `ITEMSUBBLOCK_SUBBLOCKCONTENT_0` bigint(20) DEFAULT NULL,
  `CONTENTITEMS_SUBBLOCK_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK5D2A7E7F761A1EA` (`ITEMSUBBLOCK_SUBBLOCKCONTENT_0`),
  KEY `FK5D2A7E7FE08E68C3` (`CONTENTITEMS_SUBBLOCK_HJID`),
  KEY `FK5D2A7E7F9F6C816C` (`ITEMREFCOURSE_SUBBLOCKCONTEN_0`)
)  ;

CREATE TABLE `subprogram` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID` varchar(255) DEFAULT NULL,
  `IDENT` varchar(255) DEFAULT NULL,
  `PROGRAMDURATION` varchar(255) DEFAULT NULL,
  `PROGRAMID` varchar(255) DEFAULT NULL,
  `PROGRAMNAME_SUBPROGRAM_HJID` bigint(20) DEFAULT NULL,
  `PROGRAMSTRUCTURE_SUBPROGRAM__0` bigint(20) DEFAULT NULL,
  `TEACHINGPLACE_SUBPROGRAM_HJID` bigint(20) DEFAULT NULL,
  `SUBPROGRAM_PROGRAM_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK4EF0C4449D309FCE` (`TEACHINGPLACE_SUBPROGRAM_HJID`),
  KEY `FK4EF0C444785655D4` (`PROGRAMNAME_SUBPROGRAM_HJID`),
  KEY `FK4EF0C44442A28AAA` (`PROGRAMSTRUCTURE_SUBPROGRAM__0`),
  KEY `FK4EF0C444C2296F98` (`SUBPROGRAM_PROGRAM_HJID`)
)  ;

CREATE TABLE `syllabus` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `teachingactivity` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `INFOBLOCK_TEACHINGACTIVITY_H_0` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FKFA15F55C4C310316` (`INFOBLOCK_TEACHINGACTIVITY_H_0`)
)  ;

CREATE TABLE `teachingplace` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ADR_TEACHINGPLACE_HJID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HJID`),
  KEY `FK177B9BA9E618E22` (`ADR_TEACHINGPLACE_HJID`)
)  ;

CREATE TABLE `text` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TEXT` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;

CREATE TABLE `weblink` (
  `HJID` bigint(20) NOT NULL AUTO_INCREMENT,
  `HREF` varchar(255) DEFAULT NULL,
  `LINKNAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HJID`)
)  ;


ALTER TABLE `adr`
  ADD CONSTRAINT `FKFC8FA467E46B` FOREIGN KEY (`REGION_ADR_HJID`) REFERENCES `region` (`HJID`);

ALTER TABLE `cdm`
  ADD CONSTRAINT `FK1040C35DAF2D0` FOREIGN KEY (`ORGUNIT_CDM_HJID`) REFERENCES `orgunit` (`HJID`),
  ADD CONSTRAINT `FK1040C1A2EDE30` FOREIGN KEY (`PROGRAM_CDM_HJID`) REFERENCES `program` (`HJID`);

ALTER TABLE `contactdata`
  ADD CONSTRAINT `FK82CA97AA678D0632` FOREIGN KEY (`ADR_CONTACTDATA_HJID`) REFERENCES `adr` (`HJID`),
  ADD CONSTRAINT `FK82CA97AA12B0FE52` FOREIGN KEY (`CONTACTNAME_CONTACTDATA_HJID`) REFERENCES `text` (`HJID`);

ALTER TABLE `contacts`
  ADD CONSTRAINT `FKCD35053170D743F` FOREIGN KEY (`CONTACTDATA_CONTACTS_HJID`) REFERENCES `contactdata` (`HJID`);

ALTER TABLE `course`
  ADD CONSTRAINT `FK76D5D41B8AD18637` FOREIGN KEY (`CREDITS_COURSE_HJID`) REFERENCES `credits` (`HJID`),
  ADD CONSTRAINT `FK76D5D41B43336B6B` FOREIGN KEY (`SYLLABUS_COURSE_HJID`) REFERENCES `syllabus` (`HJID`),
  ADD CONSTRAINT `FK76D5D41B4DF2EBD7` FOREIGN KEY (`TEACHINGPLACE_COURSE_HJID`) REFERENCES `teachingplace` (`HJID`),
  ADD CONSTRAINT `FK76D5D41B4F4BCBFE` FOREIGN KEY (`RECOMMENDEDPREREQUISITES_COU_0`) REFERENCES `recommendedprerequisites` (`HJID`),
  ADD CONSTRAINT `FK76D5D41B5C9FE9B5` FOREIGN KEY (`FORMALPREREQUISITES_COURSE_H_0`) REFERENCES `formalprerequisites` (`HJID`),
  ADD CONSTRAINT `FK76D5D41B64A7BCA1` FOREIGN KEY (`COURSE_CDM_HJID`) REFERENCES `cdm` (`HJID`),
  ADD CONSTRAINT `FK76D5D41BACF354F9` FOREIGN KEY (`TEACHINGACTIVITY_COURSE_HJID`) REFERENCES `teachingactivity` (`HJID`),
  ADD CONSTRAINT `FK76D5D41BBEA437F4` FOREIGN KEY (`COURSENAME_COURSE_HJID`) REFERENCES `text` (`HJID`),
  ADD CONSTRAINT `FK76D5D41BCA520C91` FOREIGN KEY (`COURSECODE_COURSE_HJID`) REFERENCES `coursecode` (`HJID`),
  ADD CONSTRAINT `FK76D5D41BD75D1F25` FOREIGN KEY (`COURSEDESCRIPTION_COURSE_HJID`) REFERENCES `coursedescription` (`HJID`),
  ADD CONSTRAINT `FK76D5D41BEAD89307` FOREIGN KEY (`LEARNINGOBJECTIVES_COURSE_HJ_0`) REFERENCES `learningobjectives` (`HJID`);

ALTER TABLE `infoblockcontentitem`
  ADD CONSTRAINT `FKFA10BD0D74BA855` FOREIGN KEY (`CONTENTITEMS_INFOBLOCK_HJID`) REFERENCES `infoblock` (`HJID`),
  ADD CONSTRAINT `FKFA10BD0D74BA2998` FOREIGN KEY (`ITEMSUBBLOCK_INFOBLOCKCONTEN_0`) REFERENCES `subblock` (`HJID`);

ALTER TABLE `orgunit`
  ADD CONSTRAINT `FKE30A02486EADAB4` FOREIGN KEY (`ORGUNITKIND_ORGUNIT_HJID`) REFERENCES `orgunitkind` (`HJID`),
  ADD CONSTRAINT `FKE30A02485AE51454` FOREIGN KEY (`WEBLINK_ORGUNIT_HJID`) REFERENCES `weblink` (`HJID`),
  ADD CONSTRAINT `FKE30A02487970BB72` FOREIGN KEY (`CONTACTS_ORGUNIT_HJID`) REFERENCES `contacts` (`HJID`),
  ADD CONSTRAINT `FKE30A0248945FAF2C` FOREIGN KEY (`ORGUNITNAME_ORGUNIT_HJID`) REFERENCES `text` (`HJID`),
  ADD CONSTRAINT `FKE30A0248B68E0FCA` FOREIGN KEY (`ORGUNITDESCRIPTION_ORGUNIT_H_0`) REFERENCES `orgunitdescription` (`HJID`);

ALTER TABLE `program`
  ADD CONSTRAINT `FK185AAA646008CBF4` FOREIGN KEY (`PROGRAMNAME_PROGRAM_HJID`) REFERENCES `text` (`HJID`),
  ADD CONSTRAINT `FK185AAA642C11FF0E` FOREIGN KEY (`LEARNINGOBJECTIVES_PROGRAM_H_0`) REFERENCES `learningobjectives` (`HJID`),
  ADD CONSTRAINT `FK185AAA642F195278` FOREIGN KEY (`QUALIFICATION_PROGRAM_HJID`) REFERENCES `qualification` (`HJID`),
  ADD CONSTRAINT `FK185AAA6440652618` FOREIGN KEY (`PROGRAMCODE_PROGRAM_HJID`) REFERENCES `programcode` (`HJID`),
  ADD CONSTRAINT `FK185AAA646B84F8CE` FOREIGN KEY (`PROGRAMDESCRIPTION_PROGRAM_H_0`) REFERENCES `programdescription` (`HJID`),
  ADD CONSTRAINT `FK185AAA64915CC8D8` FOREIGN KEY (`INFOBLOCK_PROGRAM_HJID`) REFERENCES `infoblock` (`HJID`),
  ADD CONSTRAINT `FK185AAA64CA15610C` FOREIGN KEY (`FORMALPREREQUISITES_PROGRAM__0`) REFERENCES `formalprerequisites` (`HJID`),
  ADD CONSTRAINT `FK185AAA64D5851DB8` FOREIGN KEY (`WEBLINK_PROGRAM_HJID`) REFERENCES `weblink` (`HJID`),
  ADD CONSTRAINT `FK185AAA64E92B5838` FOREIGN KEY (`TEACHINGPLACE_PROGRAM_HJID`) REFERENCES `teachingplace` (`HJID`),
  ADD CONSTRAINT `FK185AAA64FE7DC336` FOREIGN KEY (`PROGRAMSTRUCTURE_PROGRAM_HJID`) REFERENCES `programstructure` (`HJID`);

ALTER TABLE `programdescription`
  ADD CONSTRAINT `FK1E24C6F889A6D5B2` FOREIGN KEY (`SUBBLOCK_PROGRAMDESCRIPTION__0`) REFERENCES `subblock` (`HJID`);

ALTER TABLE `programsearchworditem`
  ADD CONSTRAINT `FK3D8C7A292D6979CE` FOREIGN KEY (`SEARCHWORDITEMS_PROGRAM_HJID`) REFERENCES `program` (`HJID`);

ALTER TABLE `programstructure`
  ADD CONSTRAINT `FK8D6A036FD43B165D` FOREIGN KEY (`SUBBLOCK_PROGRAMSTRUCTURE_HJ_0`) REFERENCES `subblock` (`HJID`);

ALTER TABLE `qualification`
  ADD CONSTRAINT `FK941CB5CFFDE8EE5B` FOREIGN KEY (`QUALIFICATIONNAME_QUALIFICAT_0`) REFERENCES `text` (`HJID`),
  ADD CONSTRAINT `FK941CB5CF7AB0E148` FOREIGN KEY (`QUALIFICATIONDESCRIPTION_QUA_0`) REFERENCES `qualificationdescription` (`HJID`),
  ADD CONSTRAINT `FK941CB5CFA96DB6D8` FOREIGN KEY (`STUDYQUALIFICATION_QUALIFICA_0`) REFERENCES `studyqualification` (`HJID`),
  ADD CONSTRAINT `FK941CB5CFCBBC8EB` FOREIGN KEY (`PROFESSION_QUALIFICATION_HJID`) REFERENCES `profession` (`HJID`),
  ADD CONSTRAINT `FK941CB5CFE84E9E6B` FOREIGN KEY (`DEGREE_QUALIFICATION_HJID`) REFERENCES `degree` (`HJID`),
  ADD CONSTRAINT `FK941CB5CFFC858CD` FOREIGN KEY (`CREDITS_QUALIFICATION_HJID`) REFERENCES `credits` (`HJID`);

ALTER TABLE `refprogram`
  ADD CONSTRAINT `FKB5E516919254E9C1` FOREIGN KEY (`REFPROGRAM_PROGRAMSTRUCTURE__0`) REFERENCES `programstructure` (`HJID`);

ALTER TABLE `subblock`
  ADD CONSTRAINT `FKB2D8DE4DA5D67CDD` FOREIGN KEY (`SUBBLOCK_STUDYQUALIFICATION__0`) REFERENCES `studyqualification` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4D30AF3A7C` FOREIGN KEY (`SUBBLOCK_FORMALPREREQUISITES_0`) REFERENCES `formalprerequisites` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4D71387EE2` FOREIGN KEY (`SUBBLOCK_QUALIFICATIONDESCRI_0`) REFERENCES `qualificationdescription` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4D8AF7F08A` FOREIGN KEY (`SUBBLOCK_RECOMMENDEDPREREQUI_0`) REFERENCES `recommendedprerequisites` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4D8C6BC3DD` FOREIGN KEY (`SUBBLOCK_LEARNINGOBJECTIVES__0`) REFERENCES `learningobjectives` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4D9A3DC78B` FOREIGN KEY (`SUBBLOCK_COURSEDESCRIPTION_H_0`) REFERENCES `coursedescription` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4D9EE03E9` FOREIGN KEY (`SUBBLOCK_PROFESSION_HJID`) REFERENCES `profession` (`HJID`),
  ADD CONSTRAINT `FKB2D8DE4DA166C4C9` FOREIGN KEY (`SUBBLOCK_SYLLABUS_HJID`) REFERENCES `syllabus` (`HJID`);

ALTER TABLE `subblockcontentitem`
  ADD CONSTRAINT `FK5D2A7E7F9F6C816C` FOREIGN KEY (`ITEMREFCOURSE_SUBBLOCKCONTEN_0`) REFERENCES `refcourse` (`HJID`),
  ADD CONSTRAINT `FK5D2A7E7F761A1EA` FOREIGN KEY (`ITEMSUBBLOCK_SUBBLOCKCONTENT_0`) REFERENCES `subblock` (`HJID`),
  ADD CONSTRAINT `FK5D2A7E7FE08E68C3` FOREIGN KEY (`CONTENTITEMS_SUBBLOCK_HJID`) REFERENCES `subblock` (`HJID`);

ALTER TABLE `subprogram`
  ADD CONSTRAINT `FK4EF0C444C2296F98` FOREIGN KEY (`SUBPROGRAM_PROGRAM_HJID`) REFERENCES `program` (`HJID`),
  ADD CONSTRAINT `FK4EF0C44442A28AAA` FOREIGN KEY (`PROGRAMSTRUCTURE_SUBPROGRAM__0`) REFERENCES `programstructure` (`HJID`),
  ADD CONSTRAINT `FK4EF0C444785655D4` FOREIGN KEY (`PROGRAMNAME_SUBPROGRAM_HJID`) REFERENCES `text` (`HJID`),
  ADD CONSTRAINT `FK4EF0C4449D309FCE` FOREIGN KEY (`TEACHINGPLACE_SUBPROGRAM_HJID`) REFERENCES `teachingplace` (`HJID`);

ALTER TABLE `teachingactivity`
  ADD CONSTRAINT `FKFA15F55C4C310316` FOREIGN KEY (`INFOBLOCK_TEACHINGACTIVITY_H_0`) REFERENCES `infoblock` (`HJID`);

ALTER TABLE `teachingplace`
  ADD CONSTRAINT `FK177B9BA9E618E22` FOREIGN KEY (`ADR_TEACHINGPLACE_HJID`) REFERENCES `adr` (`HJID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
