//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 10:12:58 PM CET 
//


package fr.enssat.beans;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}subBlock" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subBlock"
})
@XmlRootElement(name = "courseDescription")
@Entity(name = "CourseDescription")
@Table(name = "COURSEDESCRIPTION")
@Inheritance(strategy = InheritanceType.JOINED)
public class CourseDescription
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected List<SubBlock> subBlock;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the subBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubBlock }
     * 
     * 
     */
    @OneToMany(targetEntity = SubBlock.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SUBBLOCK_COURSEDESCRIPTION_H_0")
    public List<SubBlock> getSubBlock() {
        if (subBlock == null) {
            subBlock = new ArrayList<SubBlock>();
        }
        return this.subBlock;
    }

    /**
     * 
     * 
     */
    public void setSubBlock(List<SubBlock> subBlock) {
        this.subBlock = subBlock;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CourseDescription)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CourseDescription that = ((CourseDescription) object);
        {
            List<SubBlock> lhsSubBlock;
            lhsSubBlock = (((this.subBlock!= null)&&(!this.subBlock.isEmpty()))?this.getSubBlock():null);
            List<SubBlock> rhsSubBlock;
            rhsSubBlock = (((that.subBlock!= null)&&(!that.subBlock.isEmpty()))?that.getSubBlock():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subBlock", lhsSubBlock), LocatorUtils.property(thatLocator, "subBlock", rhsSubBlock), lhsSubBlock, rhsSubBlock)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<SubBlock> theSubBlock;
            theSubBlock = (((this.subBlock!= null)&&(!this.subBlock.isEmpty()))?this.getSubBlock():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subBlock", theSubBlock), currentHashCode, theSubBlock);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
