//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 10:12:58 PM CET 
//


package fr.enssat.beans;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _TeachingTerm_QNAME = new QName("", "teachingTerm");
    private final static QName _ProgramDuration_QNAME = new QName("", "programDuration");
    private final static QName _Street_QNAME = new QName("", "street");
    private final static QName _OrgUnitName_QNAME = new QName("", "orgUnitName");
    private final static QName _OrgUnitAcronym_QNAME = new QName("", "orgUnitAcronym");
    private final static QName _Pcode_QNAME = new QName("", "pcode");
    private final static QName _Searchword_QNAME = new QName("", "searchword");
    private final static QName _Header_QNAME = new QName("", "header");
    private final static QName _Extadr_QNAME = new QName("", "extadr");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _ProgramID_QNAME = new QName("", "programID");
    private final static QName _QualificationName_QNAME = new QName("", "qualificationName");
    private final static QName _OrgUnitID_QNAME = new QName("", "orgUnitID");
    private final static QName _Level_QNAME = new QName("", "level");
    private final static QName _ContactName_QNAME = new QName("", "contactName");
    private final static QName _Locality_QNAME = new QName("", "locality");
    private final static QName _Href_QNAME = new QName("", "href");
    private final static QName _Telephone_QNAME = new QName("", "telephone");
    private final static QName _LinkName_QNAME = new QName("", "linkName");
    private final static QName _ProgramName_QNAME = new QName("", "programName");
    private final static QName _CourseName_QNAME = new QName("", "courseName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Profession }
     * 
     */
    public Profession createProfession() {
        return new Profession();
    }

    /**
     * Create an instance of {@link SubBlock }
     * 
     */
    public SubBlock createSubBlock() {
        return new SubBlock();
    }

    /**
     * Create an instance of {@link RefCourse }
     * 
     */
    public RefCourse createRefCourse() {
        return new RefCourse();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link OrgUnit }
     * 
     */
    public OrgUnit createOrgUnit() {
        return new OrgUnit();
    }

    /**
     * Create an instance of {@link OrgUnitKind }
     * 
     */
    public OrgUnitKind createOrgUnitKind() {
        return new OrgUnitKind();
    }

    /**
     * Create an instance of {@link WebLink }
     * 
     */
    public WebLink createWebLink() {
        return new WebLink();
    }

    /**
     * Create an instance of {@link OrgUnitDescription }
     * 
     */
    public OrgUnitDescription createOrgUnitDescription() {
        return new OrgUnitDescription();
    }

    /**
     * Create an instance of {@link Contacts }
     * 
     */
    public Contacts createContacts() {
        return new Contacts();
    }

    /**
     * Create an instance of {@link ContactData }
     * 
     */
    public ContactData createContactData() {
        return new ContactData();
    }

    /**
     * Create an instance of {@link Adr }
     * 
     */
    public Adr createAdr() {
        return new Adr();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link CourseCode }
     * 
     */
    public CourseCode createCourseCode() {
        return new CourseCode();
    }

    /**
     * Create an instance of {@link CourseDescription }
     * 
     */
    public CourseDescription createCourseDescription() {
        return new CourseDescription();
    }

    /**
     * Create an instance of {@link Credits }
     * 
     */
    public Credits createCredits() {
        return new Credits();
    }

    /**
     * Create an instance of {@link LearningObjectives }
     * 
     */
    public LearningObjectives createLearningObjectives() {
        return new LearningObjectives();
    }

    /**
     * Create an instance of {@link RecommendedPrerequisites }
     * 
     */
    public RecommendedPrerequisites createRecommendedPrerequisites() {
        return new RecommendedPrerequisites();
    }

    /**
     * Create an instance of {@link FormalPrerequisites }
     * 
     */
    public FormalPrerequisites createFormalPrerequisites() {
        return new FormalPrerequisites();
    }

    /**
     * Create an instance of {@link TeachingPlace }
     * 
     */
    public TeachingPlace createTeachingPlace() {
        return new TeachingPlace();
    }

    /**
     * Create an instance of {@link Syllabus }
     * 
     */
    public Syllabus createSyllabus() {
        return new Syllabus();
    }

    /**
     * Create an instance of {@link TeachingActivity }
     * 
     */
    public TeachingActivity createTeachingActivity() {
        return new TeachingActivity();
    }

    /**
     * Create an instance of {@link InfoBlock }
     * 
     */
    public InfoBlock createInfoBlock() {
        return new InfoBlock();
    }

    /**
     * Create an instance of {@link Qualification }
     * 
     */
    public Qualification createQualification() {
        return new Qualification();
    }

    /**
     * Create an instance of {@link QualificationDescription }
     * 
     */
    public QualificationDescription createQualificationDescription() {
        return new QualificationDescription();
    }

    /**
     * Create an instance of {@link Degree }
     * 
     */
    public Degree createDegree() {
        return new Degree();
    }

    /**
     * Create an instance of {@link StudyQualification }
     * 
     */
    public StudyQualification createStudyQualification() {
        return new StudyQualification();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link ProgramCode }
     * 
     */
    public ProgramCode createProgramCode() {
        return new ProgramCode();
    }

    /**
     * Create an instance of {@link ProgramDescription }
     * 
     */
    public ProgramDescription createProgramDescription() {
        return new ProgramDescription();
    }

    /**
     * Create an instance of {@link ProgramStructure }
     * 
     */
    public ProgramStructure createProgramStructure() {
        return new ProgramStructure();
    }

    /**
     * Create an instance of {@link RefProgram }
     * 
     */
    public RefProgram createRefProgram() {
        return new RefProgram();
    }

    /**
     * Create an instance of {@link SubProgram }
     * 
     */
    public SubProgram createSubProgram() {
        return new SubProgram();
    }

    /**
     * Create an instance of {@link CDM }
     * 
     */
    public CDM createCDM() {
        return new CDM();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "teachingTerm")
    public JAXBElement<String> createTeachingTerm(String value) {
        return new JAXBElement<String>(_TeachingTerm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "programDuration")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProgramDuration(String value) {
        return new JAXBElement<String>(_ProgramDuration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orgUnitName")
    public JAXBElement<Text> createOrgUnitName(Text value) {
        return new JAXBElement<Text>(_OrgUnitName_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orgUnitAcronym")
    public JAXBElement<String> createOrgUnitAcronym(String value) {
        return new JAXBElement<String>(_OrgUnitAcronym_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pcode")
    public JAXBElement<BigInteger> createPcode(BigInteger value) {
        return new JAXBElement<BigInteger>(_Pcode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "searchword")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSearchword(String value) {
        return new JAXBElement<String>(_Searchword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "header")
    public JAXBElement<String> createHeader(String value) {
        return new JAXBElement<String>(_Header_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extadr")
    public JAXBElement<String> createExtadr(String value) {
        return new JAXBElement<String>(_Extadr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "programID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProgramID(String value) {
        return new JAXBElement<String>(_ProgramID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qualificationName")
    public JAXBElement<Text> createQualificationName(Text value) {
        return new JAXBElement<Text>(_QualificationName_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orgUnitID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOrgUnitID(String value) {
        return new JAXBElement<String>(_OrgUnitID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "level")
    public JAXBElement<String> createLevel(String value) {
        return new JAXBElement<String>(_Level_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactName")
    public JAXBElement<Text> createContactName(Text value) {
        return new JAXBElement<Text>(_ContactName_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "locality")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocality(String value) {
        return new JAXBElement<String>(_Locality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "href")
    public JAXBElement<String> createHref(String value) {
        return new JAXBElement<String>(_Href_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "telephone")
    public JAXBElement<String> createTelephone(String value) {
        return new JAXBElement<String>(_Telephone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkName")
    public JAXBElement<String> createLinkName(String value) {
        return new JAXBElement<String>(_LinkName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "programName")
    public JAXBElement<Text> createProgramName(Text value) {
        return new JAXBElement<Text>(_ProgramName_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "courseName")
    public JAXBElement<Text> createCourseName(Text value) {
        return new JAXBElement<Text>(_CourseName_QNAME, Text.class, null, value);
    }

}
