//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 10:12:58 PM CET 
//


package fr.enssat.beans;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}header"/>
 *         &lt;choice>
 *           &lt;element ref="{}subBlock"/>
 *           &lt;element ref="{}refProgram" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "subBlock",
    "refProgram"
})
@XmlRootElement(name = "programStructure")
@Entity(name = "ProgramStructure")
@Table(name = "PROGRAMSTRUCTURE")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProgramStructure
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected String header;
    protected SubBlock subBlock;
    protected List<RefProgram> refProgram;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "HEADER", length = 255)
    public String getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader(String value) {
        this.header = value;
    }

    /**
     * Gets the value of the subBlock property.
     * 
     * @return
     *     possible object is
     *     {@link SubBlock }
     *     
     */
    @ManyToOne(targetEntity = SubBlock.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SUBBLOCK_PROGRAMSTRUCTURE_HJ_0")
    public SubBlock getSubBlock() {
        return subBlock;
    }

    /**
     * Sets the value of the subBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubBlock }
     *     
     */
    public void setSubBlock(SubBlock value) {
        this.subBlock = value;
    }

    /**
     * Gets the value of the refProgram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refProgram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefProgram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefProgram }
     * 
     * 
     */
    @OneToMany(targetEntity = RefProgram.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "REFPROGRAM_PROGRAMSTRUCTURE__0")
    public List<RefProgram> getRefProgram() {
        if (refProgram == null) {
            refProgram = new ArrayList<RefProgram>();
        }
        return this.refProgram;
    }

    /**
     * 
     * 
     */
    public void setRefProgram(List<RefProgram> refProgram) {
        this.refProgram = refProgram;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ProgramStructure)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProgramStructure that = ((ProgramStructure) object);
        {
            String lhsHeader;
            lhsHeader = this.getHeader();
            String rhsHeader;
            rhsHeader = that.getHeader();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "header", lhsHeader), LocatorUtils.property(thatLocator, "header", rhsHeader), lhsHeader, rhsHeader)) {
                return false;
            }
        }
        {
            SubBlock lhsSubBlock;
            lhsSubBlock = this.getSubBlock();
            SubBlock rhsSubBlock;
            rhsSubBlock = that.getSubBlock();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subBlock", lhsSubBlock), LocatorUtils.property(thatLocator, "subBlock", rhsSubBlock), lhsSubBlock, rhsSubBlock)) {
                return false;
            }
        }
        {
            List<RefProgram> lhsRefProgram;
            lhsRefProgram = (((this.refProgram!= null)&&(!this.refProgram.isEmpty()))?this.getRefProgram():null);
            List<RefProgram> rhsRefProgram;
            rhsRefProgram = (((that.refProgram!= null)&&(!that.refProgram.isEmpty()))?that.getRefProgram():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refProgram", lhsRefProgram), LocatorUtils.property(thatLocator, "refProgram", rhsRefProgram), lhsRefProgram, rhsRefProgram)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theHeader;
            theHeader = this.getHeader();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "header", theHeader), currentHashCode, theHeader);
        }
        {
            SubBlock theSubBlock;
            theSubBlock = this.getSubBlock();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subBlock", theSubBlock), currentHashCode, theSubBlock);
        }
        {
            List<RefProgram> theRefProgram;
            theRefProgram = (((this.refProgram!= null)&&(!this.refProgram.isEmpty()))?this.getRefProgram():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refProgram", theRefProgram), currentHashCode, theRefProgram);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
