//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 10:12:58 PM CET 
//


package fr.enssat.beans;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.jvnet.hyperjaxb3.item.MixedItem;
import org.jvnet.hyperjaxb3.item.MixedItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}subBlock"/>
 *         &lt;element ref="{}refCourse"/>
 *       &lt;/choice>
 *       &lt;attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "subBlock")
@Entity(name = "SubBlock")
@Table(name = "SUBBLOCK")
@Inheritance(strategy = InheritanceType.JOINED)
public class SubBlock implements Equals, HashCode
{

    @XmlElementRefs({
        @XmlElementRef(name = "subBlock", type = SubBlock.class),
        @XmlElementRef(name = "refCourse", type = RefCourse.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "userDefined")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String userDefined;
    @XmlTransient
    protected Long hjid;
    protected transient List<SubBlock.SubBlockContentItem> contentItems;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubBlock }
     * {@link String }
     * {@link RefCourse }
     * 
     * 
     */
    @Transient
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * 
     * 
     */
    public void setContent(List<Object> content) {
        this.content = content;
    }

    /**
     * Gets the value of the userDefined property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "USERDEFINED", length = 255)
    public String getUserDefined() {
        return userDefined;
    }

    /**
     * Sets the value of the userDefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefined(String value) {
        this.userDefined = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = SubBlock.SubBlockContentItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CONTENTITEMS_SUBBLOCK_HJID")
    public List<SubBlock.SubBlockContentItem> getContentItems() {
        if (this.contentItems == null) {
            this.contentItems = new ArrayList<SubBlock.SubBlockContentItem>();
        }
        if (MixedItemUtils.shouldBeWrapped(this.content)) {
            this.content = MixedItemUtils.wrap(this.content, this.contentItems, SubBlock.SubBlockContentItem.class);
        }
        return this.contentItems;
    }

    public void setContentItems(List<SubBlock.SubBlockContentItem> value) {
        this.content = null;
        this.contentItems = null;
        this.contentItems = value;
        if (this.contentItems == null) {
            this.contentItems = new ArrayList<SubBlock.SubBlockContentItem>();
        }
        if (MixedItemUtils.shouldBeWrapped(this.content)) {
            this.content = MixedItemUtils.wrap(this.content, this.contentItems, SubBlock.SubBlockContentItem.class);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof SubBlock)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final SubBlock that = ((SubBlock) object);
        {
            List<Object> lhsContent;
            lhsContent = (((this.content!= null)&&(!this.content.isEmpty()))?this.getContent():null);
            List<Object> rhsContent;
            rhsContent = (((that.content!= null)&&(!that.content.isEmpty()))?that.getContent():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "content", lhsContent), LocatorUtils.property(thatLocator, "content", rhsContent), lhsContent, rhsContent)) {
                return false;
            }
        }
        {
            String lhsUserDefined;
            lhsUserDefined = this.getUserDefined();
            String rhsUserDefined;
            rhsUserDefined = that.getUserDefined();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userDefined", lhsUserDefined), LocatorUtils.property(thatLocator, "userDefined", rhsUserDefined), lhsUserDefined, rhsUserDefined)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<Object> theContent;
            theContent = (((this.content!= null)&&(!this.content.isEmpty()))?this.getContent():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "content", theContent), currentHashCode, theContent);
        }
        {
            String theUserDefined;
            theUserDefined = this.getUserDefined();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userDefined", theUserDefined), currentHashCode, theUserDefined);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "SubBlock$SubBlockContentItem")
    @Table(name = "SUBBLOCKCONTENTITEM")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class SubBlockContentItem
        implements MixedItem<Object>
    {

        @XmlElementRefs({
            @XmlElementRef(name = "subBlock", type = SubBlock.class),
            @XmlElementRef(name = "refCourse", type = RefCourse.class)
        })
        protected Object item;
        @XmlAttribute(name = "Text")
        protected String text;
        @XmlTransient
        protected Long hjid;

        /**
         * 
         * 
         * @return
         *     possible object is
         *     {@link SubBlock }
         *     {@link RefCourse }
         *     
         */
        @Transient
        public Object getItem() {
            return item;
        }

        /**
         * 
         * 
         * @param value
         *     allowed object is
         *     {@link SubBlock }
         *     {@link RefCourse }
         *     
         */
        public void setItem(Object value) {
            this.item = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "TEXT")
        @Lob
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        @ManyToOne(targetEntity = SubBlock.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "ITEMSUBBLOCK_SUBBLOCKCONTENT_0")
        public SubBlock getItemSubBlock() {
            if (this.getItem() instanceof SubBlock) {
                return ((SubBlock) this.getItem());
            } else {
                return null;
            }
        }

        public void setItemSubBlock(SubBlock target) {
            if (target!= null) {
                setItem(target);
            }
        }

        @ManyToOne(targetEntity = RefCourse.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "ITEMREFCOURSE_SUBBLOCKCONTEN_0")
        public RefCourse getItemRefCourse() {
            if (this.getItem() instanceof RefCourse) {
                return ((RefCourse) this.getItem());
            } else {
                return null;
            }
        }

        public void setItemRefCourse(RefCourse target) {
            if (target!= null) {
                setItem(target);
            }
        }

    }

}
