//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 10:12:58 PM CET 
//


package fr.enssat.beans;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}programID"/>
 *         &lt;element ref="{}programName"/>
 *         &lt;element ref="{}teachingPlace"/>
 *         &lt;element ref="{}programDuration"/>
 *         &lt;element ref="{}programStructure"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ident" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "programID",
    "programName",
    "teachingPlace",
    "programDuration",
    "programStructure"
})
@XmlRootElement(name = "subProgram")
@Entity(name = "SubProgram")
@Table(name = "SUBPROGRAM")
@Inheritance(strategy = InheritanceType.JOINED)
public class SubProgram
    implements Equals, HashCode
{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String programID;
    @XmlElement(required = true)
    protected Text programName;
    @XmlElement(required = true)
    protected TeachingPlace teachingPlace;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String programDuration;
    @XmlElement(required = true)
    protected ProgramStructure programStructure;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "ident", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ident;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the programID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROGRAMID", length = 255)
    public String getProgramID() {
        return programID;
    }

    /**
     * Sets the value of the programID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramID(String value) {
        this.programID = value;
    }

    /**
     * Gets the value of the programName property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    @ManyToOne(targetEntity = Text.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PROGRAMNAME_SUBPROGRAM_HJID")
    public Text getProgramName() {
        return programName;
    }

    /**
     * Sets the value of the programName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setProgramName(Text value) {
        this.programName = value;
    }

    /**
     * Gets the value of the teachingPlace property.
     * 
     * @return
     *     possible object is
     *     {@link TeachingPlace }
     *     
     */
    @ManyToOne(targetEntity = TeachingPlace.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TEACHINGPLACE_SUBPROGRAM_HJID")
    public TeachingPlace getTeachingPlace() {
        return teachingPlace;
    }

    /**
     * Sets the value of the teachingPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeachingPlace }
     *     
     */
    public void setTeachingPlace(TeachingPlace value) {
        this.teachingPlace = value;
    }

    /**
     * Gets the value of the programDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PROGRAMDURATION", length = 255)
    public String getProgramDuration() {
        return programDuration;
    }

    /**
     * Sets the value of the programDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramDuration(String value) {
        this.programDuration = value;
    }

    /**
     * Gets the value of the programStructure property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramStructure }
     *     
     */
    @ManyToOne(targetEntity = ProgramStructure.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PROGRAMSTRUCTURE_SUBPROGRAM__0")
    public ProgramStructure getProgramStructure() {
        return programStructure;
    }

    /**
     * Sets the value of the programStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramStructure }
     *     
     */
    public void setProgramStructure(ProgramStructure value) {
        this.programStructure = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ID", length = 255)
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "IDENT", length = 255)
    public String getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdent(String value) {
        this.ident = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof SubProgram)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final SubProgram that = ((SubProgram) object);
        {
            String lhsProgramID;
            lhsProgramID = this.getProgramID();
            String rhsProgramID;
            rhsProgramID = that.getProgramID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "programID", lhsProgramID), LocatorUtils.property(thatLocator, "programID", rhsProgramID), lhsProgramID, rhsProgramID)) {
                return false;
            }
        }
        {
            Text lhsProgramName;
            lhsProgramName = this.getProgramName();
            Text rhsProgramName;
            rhsProgramName = that.getProgramName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "programName", lhsProgramName), LocatorUtils.property(thatLocator, "programName", rhsProgramName), lhsProgramName, rhsProgramName)) {
                return false;
            }
        }
        {
            TeachingPlace lhsTeachingPlace;
            lhsTeachingPlace = this.getTeachingPlace();
            TeachingPlace rhsTeachingPlace;
            rhsTeachingPlace = that.getTeachingPlace();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "teachingPlace", lhsTeachingPlace), LocatorUtils.property(thatLocator, "teachingPlace", rhsTeachingPlace), lhsTeachingPlace, rhsTeachingPlace)) {
                return false;
            }
        }
        {
            String lhsProgramDuration;
            lhsProgramDuration = this.getProgramDuration();
            String rhsProgramDuration;
            rhsProgramDuration = that.getProgramDuration();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "programDuration", lhsProgramDuration), LocatorUtils.property(thatLocator, "programDuration", rhsProgramDuration), lhsProgramDuration, rhsProgramDuration)) {
                return false;
            }
        }
        {
            ProgramStructure lhsProgramStructure;
            lhsProgramStructure = this.getProgramStructure();
            ProgramStructure rhsProgramStructure;
            rhsProgramStructure = that.getProgramStructure();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "programStructure", lhsProgramStructure), LocatorUtils.property(thatLocator, "programStructure", rhsProgramStructure), lhsProgramStructure, rhsProgramStructure)) {
                return false;
            }
        }
        {
            String lhsId;
            lhsId = this.getId();
            String rhsId;
            rhsId = that.getId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                return false;
            }
        }
        {
            String lhsIdent;
            lhsIdent = this.getIdent();
            String rhsIdent;
            rhsIdent = that.getIdent();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ident", lhsIdent), LocatorUtils.property(thatLocator, "ident", rhsIdent), lhsIdent, rhsIdent)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theProgramID;
            theProgramID = this.getProgramID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "programID", theProgramID), currentHashCode, theProgramID);
        }
        {
            Text theProgramName;
            theProgramName = this.getProgramName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "programName", theProgramName), currentHashCode, theProgramName);
        }
        {
            TeachingPlace theTeachingPlace;
            theTeachingPlace = this.getTeachingPlace();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "teachingPlace", theTeachingPlace), currentHashCode, theTeachingPlace);
        }
        {
            String theProgramDuration;
            theProgramDuration = this.getProgramDuration();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "programDuration", theProgramDuration), currentHashCode, theProgramDuration);
        }
        {
            ProgramStructure theProgramStructure;
            theProgramStructure = this.getProgramStructure();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "programStructure", theProgramStructure), currentHashCode, theProgramStructure);
        }
        {
            String theId;
            theId = this.getId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
        }
        {
            String theIdent;
            theIdent = this.getIdent();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ident", theIdent), currentHashCode, theIdent);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
